services:
  influxdb:
    image: influxdb:3-core
    container_name: museumguard-influxdb
    ports:
      - "8181:8181"
    command:
      - influxdb3
      - serve
      - --node-id=node0
      - --object-store=file
      - --data-dir=/var/lib/influxdb3/data
      - --admin-token-file=/run/secrets/admin-token
    secrets:
      - admin-token
    volumes:
      - type: bind
        source: ./.influxdb3/data
        target: /var/lib/influxdb3/data
    restart: unless-stopped

  grafana:
    image: grafana/grafana
    container_name: museumguard-grafana
    restart: unless-stopped
    volumes:
      - grafana_data:/var/lib/grafana
    depends_on:
      - influxdb
    environment:
      GF_SECURITY_ADMIN_USER: admin
      GF_SECURITY_ADMIN_PASSWORD: admin
    ports:
      - '3000:3000'

secrets:
  admin-token:
    file: ./admin-token.json

volumes:
  grafana_data: